### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by computerjazz** [nhevia/discord-styled-releases#9]
Hi! Thanks for a very useful GH action. In the last few days I've noticed failures, maybe related to the big diff that just landed on `main`? I'm going to try pinning to v1.2.1 and see if that fixes the issue.

```
0s
Run nhevia/discord-styled-releases@main
  with:
    webhook_id: ***
    webhook_token: ***
/home/runner/work/_actions/nhevia/discord-styled-releases/main/dist/index.js:5909
  /******/ 			__webpack_modules__[moduleId].call(module.exports, module, module.exports, __nccwpck_require__);
           			                              ^

TypeError: Cannot read property 'call' of undefined
    at __nccwpck_require__ (/home/runner/work/_actions/nhevia/discord-styled-releases/main/dist/index.js:5909:45)
  ....
...
```

related: 
- https://github.com/webpack/webpack/issues/11725
- https://github.com/webpack/webpack/issues/11277

**Comment by computerjazz** [comment]
update: pinning to 1.2.1 restored functionality, so something in 1.2.2 seems to be the culprit

**Comment by nhevia** [comment]
Thanks for the report! I'll check it out.

**Comment by devrsw** [comment]
We can also confirm this exact issue.

**Comment by nhevia** [comment]
Fix is merged and `main` is working back already.

The issue is originated on the fact that github requires dependencies to be built already when the action executes. This means that the source code needs to be generated and if a dep version changes, the new action release will contain a lot of changes.

I've locked the dependency version to prevent massive diffs going onwards, but since the file is huge and the diffs are impossible to check, there were 2 wrong bindings (ncc as a tool creates some bindings at the end of the file to functions above).

This should not be a problem for now on, unless new dependencies are added later on (which they shouldnt I'm practically using github action packages)
